# Generated by Django 4.2.11 on 2024-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Venue",
        ),
        migrations.AlterField(
            model_name="artist",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
