# Generated by Django 4.2.11 on 2024-03-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_venue_concert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="venue",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Venue",
        ),
    ]
