# Generated by Django 4.2.11 on 2024-03-26 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0009_concert"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Concert",
            new_name="AddConcert",
        ),
    ]
