# Generated by Django 4.2.11 on 2024-04-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0010_rename_concert_addconcert"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="addconcert",
            index=models.Index(
                fields=["date", "artist"], name="myApp_addco_date_f55952_idx"
            ),
        ),
    ]
